```yaml
name: Workflow to build and Review the code using SonarCloud

on:
  workflow_dispatch:
    inputs:
      job_maven:
        description: 'Run the maven job'
        required: true
        type: boolean

      job_sonar:
        description: 'Run the sonar job'
        required: true
        type: boolean

jobs:

  job_maven:
    if: ${{ inputs.job_maven }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code on runner VM
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the code using Maven
        run: mvn clean install


  job_sonar:
    if: ${{ inputs.job_sonar }}
    needs: job_maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code on runner VM
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test using Maven
        run: mvn -B clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=sumitorganization-121286_sumitjain1212
            -Dsonar.organization=sumitorganization-121286

      - name: Check SonarCloud report
        run: |
          echo "Checking .scannerwork..."

          ls -la

          if [ -d ".scannerwork" ]; then
            echo ".scannerwork directory found:"
            ls -la .scannerwork
          else
            echo "ERROR: .scannerwork directory does not exist"
            exit 1
          fi

          if [ -f ".scannerwork/report-task.txt" ]; then
            echo ""
            echo "report-task.txt found:"
            echo "----------------------------------------"
            cat .scannerwork/report-task.txt
            echo "----------------------------------------"
          else
            echo "ERROR: .scannerwork/report-task.txt does not exist"
            exit 1
          fi

      - name: SonarCloud Quality Gate
        id: sonarqube-quality-gate-check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.1
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: java-artifacts
          path: target/*.war
```
