name: Workflow to build and Review the code using Sonarqube

on:
  workflow_dispatch:
    inputs:
      job_maven:
        description: 'Run the maven job'
        required: true
        type: boolean
      job_sonar:
        description: 'Run the sonar job'
        required: true
        type: boolean

jobs:

  job_maven:
    if: ${{ inputs.job_maven }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code on runner VM
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the code using maven
        run: mvn clean install


  job_sonar:
    if: ${{ inputs.job_sonar }}
    needs: job_maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code on runner VM
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Code Coverage using SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.2.0.4988:sonar \
            -Dsonar.projectKey=sumitorganization-121286_sumitjain1212 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=sumitorganization-121286 \
            -Dsonar.token=$SONAR_TOKEN

      - name: Check SonarQube report
        run: |
          echo "Checking .scannerwork..."
          ls -la
          ls -la .scannerwork || true

          if [ -f .scannerwork/report-task.txt ]; then
            echo "report-task.txt found:"
            cat .scannerwork/report-task.txt
          else
            echo "ERROR: .scannerwork/report-task.txt does not exist"
            exit 1
          fi

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.1
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: java-artifacts
          path: target/*.war
